export const LOADING_VISIBLE = "LOADING_VISIBLE;";
export const SAVE_BUILD = "SAVE_BUILD";
export const ACTIVE_BUILD_TAB = "ACTIVE_BUILD_TAB";
export const VIEWER_CARDS_TO_FRONT = "VIEWER_CARDS_TO_FRONT";
export const SET_CURRENT_BUILD = "SET_CURRENT_BUILD";
