// UTILS

export const LOADING_VISIBLE = "LOADING_VISIBLE;";
export const SET_CONGRATS_MSGS = "SET_CONGRATS_MSGS";
export const MODAL = "MODAL";
export const GAME_NAME = "GAME_NAME";
export const NUM_OF_PAIRS = "NUM_OF_PAIRS";

// GAMES

export const SAVE_BUILT_GAME = "SAVE_BUILT_GAME";
export const SAVE_BUILT_RULES = "SAVE_BUILT_RULES";
export const SAVE_BUILT_PAIRS = "SAVE_BUILT_PAIRS";
export const SAVE_BUILT_BACK_IMG = "SAVE_BUILT_BACK_IMG";

// GAME BUILDER

export const ACTIVE_BUILD_TAB = "ACTIVE_BUILD_TAB";
export const UPLOADED_IMAGES = "UPLOADED_IMAGES";
export const SET_ACTIVE_IMAGE = "SET_ACTIVE_IMAGE";
export const SET_CARD_CAPTIONS = "SET_CARD_CAPTIONS";
export const VIEWER_CARDS_TO_FRONT = "VIEWER_CARDS_TO_FRONT";

// SETUP GAME

export const SETUP_GAME = "SETUP_GAME";
export const NUM_OF_PLAYERS = "NUM_OF_PLAYERS";
export const PLAYER_NAMES = "PLAYER_NAMES";
export const ACTIVE_GAME = "ACTIVE_GAME";
export const SET_ACTIVE_CARD_1 = "SET_ACTIVE_CARD_1";
export const SET_ACTIVE_CARD_2 = "SET_ACTIVE_CARD_2";
export const SET_ACTIVE_PLAYER = "SET_ACTIVE_PLAYER";
export const SET_SCORE = "SET_SCORE";
export const FETCH_PAIRS = "FETCH_PAIRS";

// GAME FINISH

export const SET_GAME_FINISH = "SET_GAME_FINISH";
